package app

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "<!-- Generated by ai-sync. Do not edit directly; source is .ai/. -->\n\n"

var allTargets = []string{"claude", "codex", "kiro"}

// Run executes ai-sync in workdir with CLI-style args and returns user-facing output.
func Run(workdir string, args []string) (string, error) {
	if len(args) > 0 && args[0] == "init" {
		return initSource(workdir)
	}
	if len(args) > 0 && args[0] == "convention" {
		return conventionText(), nil
	}
	if wantsHelp(args) {
		return helpText(), nil
	}

	var opts options
	flags := flag.NewFlagSet("ai-sync", flag.ContinueOnError)
	var flagOutput bytes.Buffer
	flags.SetOutput(&flagOutput)
	flags.StringVar(&opts.target, "target", "", "target to generate: claude, codex, or kiro")
	flags.BoolVar(&opts.dryRun, "dry-run", false, "show changes without writing")
	if err := flags.Parse(args); err != nil {
		return strings.TrimSpace(flagOutput.String()), err
	}
	if flags.NArg() > 0 {
		return "", fmt.Errorf("unknown command %q", flags.Arg(0))
	}

	source, err := loadSource(workdir)
	if err != nil {
		return "", err
	}

	targets, err := selectedTargets(opts.target)
	if err != nil {
		return "", err
	}

	var outputs []generatedFile
	for _, target := range targets {
		targetOutputs, err := renderTarget(target, source)
		if err != nil {
			return "", err
		}
		outputs = append(outputs, targetOutputs...)
	}
	outputs = appendGeneratedManifests(outputs)

	changes, err := applyOutputs(workdir, outputs, opts.dryRun)
	if err != nil {
		return "", err
	}
	pruned, err := pruneTargetOutputs(workdir, targets, outputs, opts.dryRun)
	if err != nil {
		return "", err
	}
	changes = append(changes, pruned...)
	if len(changes) == 0 {
		return "no changes\n", nil
	}
	return strings.Join(changes, "\n") + "\n", nil
}

func wantsHelp(args []string) bool {
	for _, arg := range args {
		if arg == "--help" || arg == "-h" {
			return true
		}
	}
	return false
}

func helpText() string {
	return `ai-sync keeps AI-agent configuration in one canonical .ai/ directory.

Usage:
  ai-sync [--target claude|codex|kiro] [--dry-run]
  ai-sync init
  ai-sync convention

Commands:
  init              scaffold a starter .ai/ directory
  convention        print the .ai authoring convention for humans or AI agents

Options:
  --target string   target to generate: claude, codex, or kiro
  --dry-run         show changes without writing
  --help, -h        show help

Examples:
  ai-sync init
  ai-sync convention
  ai-sync
  ai-sync --target codex
  ai-sync --dry-run

See README.md for the .ai authoring standard.
`
}

func conventionText() string {
	return `# ai-sync .ai Authoring Convention

Create a canonical .ai/ directory for the project. ai-sync reads this directory and generates the agent-specific files for Claude Code, Codex, and Kiro.

## Goal

Use .ai/ as the single source of truth for AI-agent configuration. Do not create generated agent files directly, such as CLAUDE.md, AGENTS.md, .mcp.json, .codex/config.toml, or .kiro/settings/mcp.json.

## Required structure

` + "```txt" + `
.ai/
  project.md
  mcp.yaml
  targets/
    claude.md
    codex.md
    kiro.md
  skills/
    <name>/
      SKILL.md
      scripts/
      references/
      assets/
` + "```" + `

## Files

| File | Purpose |
| --- | --- |
| .ai/project.md | Shared project rules, architecture, commands, conventions, and review expectations. |
| .ai/mcp.yaml | Shared MCP server definitions. Reference environment variables instead of hardcoding secrets. |
| .ai/targets/claude.md | Claude Code-specific guidance only. |
| .ai/targets/codex.md | Codex-specific guidance only. |
| .ai/targets/kiro.md | Kiro-specific guidance only. |
| .ai/skills/<name>/SKILL.md | Reusable workflow instructions copied into each agent's expected skill format. |

## Authoring rules

- Put shared guidance in .ai/project.md.
- Put agent-specific overrides in .ai/targets/<target>.md.
- Put reusable workflows in .ai/skills/<name>/SKILL.md.
- Keep secrets out of .ai/mcp.yaml; use environment variables.
- Do not create generated agent files directly. Run ai-sync after creating or editing .ai/.

## Suggested prompt for an AI agent

Create the .ai/ directory using the ai-sync convention. Add shared project guidance to .ai/project.md, define MCP servers in .ai/mcp.yaml, put agent-specific instructions under .ai/targets/, and add reusable workflows under .ai/skills/<name>/SKILL.md. Do not create CLAUDE.md, AGENTS.md, .codex/config.toml, .mcp.json, or .kiro/settings/mcp.json directly.
`
}

type options struct {
	target string
	dryRun bool
}

type source struct {
	Project string
	Targets map[string]string
	MCP     mcpConfig
	Skills  []skill
}

type mcpConfig struct {
	Servers map[string]mcpServer `yaml:"servers"`
}

type mcpServer struct {
	Command string            `yaml:"command"`
	Args    []string          `yaml:"args"`
	Env     map[string]string `yaml:"env"`
}

type skill struct {
	Name  string
	Files map[string][]byte
}

type generatedFile struct {
	Path    string
	Content []byte
}

func initSource(workdir string) (string, error) {
	files := []generatedFile{
		{Path: ".ai/project.md", Content: []byte("# Project\n\nDescribe shared stack, commands, conventions, and review expectations here.\n")},
		{Path: ".ai/mcp.yaml", Content: []byte("servers: {}\n")},
		{Path: ".ai/targets/claude.md", Content: []byte("# Claude Code\n\nAdd Claude-specific guidance here.\n")},
		{Path: ".ai/targets/codex.md", Content: []byte("# Codex\n\nAdd Codex-specific guidance here.\n")},
		{Path: ".ai/targets/kiro.md", Content: []byte("# Kiro\n\nAdd Kiro-specific guidance here.\n")},
		{Path: ".ai/skills/example/SKILL.md", Content: []byte("---\nname: \"example\"\ndescription: \"Explain when this reusable workflow should be used.\"\n---\n\n# Example Skill\n\nDocument the workflow here.\n")},
	}
	changes, err := applyOutputs(workdir, files, false)
	if err != nil {
		return "", err
	}
	if len(changes) == 0 {
		return ".ai already exists\n", nil
	}
	return "created .ai\n" + strings.Join(changes, "\n") + "\n", nil
}

func loadSource(workdir string) (source, error) {
	root := filepath.Join(workdir, ".ai")
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return source{}, errors.New("canonical source .ai/ not found; run `ai-sync init` first")
		}
		return source{}, err
	}

	project, err := readRequiredText(filepath.Join(root, "project.md"))
	if err != nil {
		return source{}, err
	}

	mcpBytes, err := os.ReadFile(filepath.Join(root, "mcp.yaml"))
	if err != nil {
		return source{}, fmt.Errorf("read .ai/mcp.yaml: %w", err)
	}
	var mcp mcpConfig
	if err := yaml.Unmarshal(mcpBytes, &mcp); err != nil {
		return source{}, fmt.Errorf("parse .ai/mcp.yaml: %w", err)
	}
	if mcp.Servers == nil {
		mcp.Servers = map[string]mcpServer{}
	}

	targets := make(map[string]string, len(allTargets))
	for _, target := range allTargets {
		path := filepath.Join(root, "targets", target+".md")
		text, err := readOptionalText(path)
		if err != nil {
			return source{}, err
		}
		targets[target] = text
	}

	skills, err := loadSkills(filepath.Join(root, "skills"))
	if err != nil {
		return source{}, err
	}

	return source{Project: project, Targets: targets, MCP: mcp, Skills: skills}, nil
}

func readRequiredText(path string) (string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", filepath.ToSlash(path), err)
	}
	return normalizeMarkdown(string(contents)), nil
}

func readOptionalText(path string) (string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("read %s: %w", filepath.ToSlash(path), err)
	}
	return normalizeMarkdown(string(contents)), nil
}

func normalizeMarkdown(text string) string {
	return strings.TrimSpace(strings.ReplaceAll(text, "\r\n", "\n")) + "\n"
}

func loadSkills(root string) ([]skill, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .ai/skills: %w", err)
	}

	var skills []skill
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		name := entry.Name()
		files := map[string][]byte{}
		skillRoot := filepath.Join(root, name)
		if err := filepath.WalkDir(skillRoot, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(skillRoot, path)
			if err != nil {
				return err
			}
			contents, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			files[filepath.ToSlash(rel)] = contents
			return nil
		}); err != nil {
			return nil, fmt.Errorf("read skill %s: %w", name, err)
		}
		skills = append(skills, skill{Name: name, Files: files})
	}
	sort.Slice(skills, func(i, j int) bool { return skills[i].Name < skills[j].Name })
	return skills, nil
}

func selectedTargets(target string) ([]string, error) {
	if target == "" {
		return append([]string(nil), allTargets...), nil
	}
	for _, known := range allTargets {
		if target == known {
			return []string{target}, nil
		}
	}
	return nil, fmt.Errorf("unknown target %q; expected claude, codex, or kiro", target)
}

func renderTarget(target string, source source) ([]generatedFile, error) {
	switch target {
	case "claude":
		return renderClaude(source)
	case "codex":
		return renderCodex(source)
	case "kiro":
		return renderKiro(source)
	default:
		return nil, fmt.Errorf("unknown target %q", target)
	}
}

func renderClaude(source source) ([]generatedFile, error) {
	files := []generatedFile{
		{Path: "CLAUDE.md", Content: renderGuidance("Claude Code", source.Project, source.Targets["claude"])},
		{Path: ".claude/settings.json", Content: mustJSON(map[string]any{"permissions": map[string]any{}})},
		{Path: ".mcp.json", Content: mustJSON(map[string]any{"mcpServers": mcpServersJSON(source.MCP)})},
	}
	files = append(files, copySkills(source.Skills, ".claude/skills", false)...)
	return files, nil
}

func renderCodex(source source) ([]generatedFile, error) {
	files := []generatedFile{
		{Path: "AGENTS.md", Content: renderGuidance("Codex", source.Project, source.Targets["codex"])},
		{Path: ".codex/config.toml", Content: renderCodexConfig(source.MCP)},
	}
	files = append(files, copySkills(source.Skills, ".agents/skills", false)...)
	return files, nil
}

func renderKiro(source source) ([]generatedFile, error) {
	files := []generatedFile{
		{Path: ".kiro/steering/project-conventions.md", Content: renderGuidance("Kiro", source.Project, source.Targets["kiro"])},
		{Path: ".kiro/settings/mcp.json", Content: mustJSON(map[string]any{"mcpServers": mcpServersJSON(source.MCP)})},
	}
	for _, sourceSkill := range source.Skills {
		files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(".kiro/powers", sourceSkill.Name, "POWER.md")), Content: renderKiroPower(sourceSkill)})
		for _, rel := range sortedFileNames(sourceSkill.Files) {
			if rel == "SKILL.md" {
				continue
			}
			files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(".kiro/powers", sourceSkill.Name, rel)), Content: sourceSkill.Files[rel]})
		}
	}
	return files, nil
}

func renderGuidance(target, project, override string) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# ")
	b.WriteString(target)
	b.WriteString(" Agent Instructions\n\n")
	b.WriteString("## Shared Project Guidance\n\n")
	b.WriteString(strings.TrimSpace(project))
	b.WriteString("\n")
	if strings.TrimSpace(override) != "" {
		b.WriteString("\n## Target-Specific Guidance\n\n")
		b.WriteString(strings.TrimSpace(override))
		b.WriteString("\n")
	}
	return []byte(b.String())
}

func renderCodexConfig(mcp mcpConfig) []byte {
	var b strings.Builder
	b.WriteString("# Generated by ai-sync. Do not edit directly; source is .ai/.\n")
	for _, name := range sortedServerNames(mcp.Servers) {
		server := mcp.Servers[name]
		b.WriteString("\n[mcp_servers.")
		b.WriteString(tomlBareKey(name))
		b.WriteString("]\n")
		b.WriteString("command = ")
		b.WriteString(tomlString(server.Command))
		b.WriteString("\n")
		if len(server.Args) > 0 {
			b.WriteString("args = ")
			b.WriteString(tomlStringArray(server.Args))
			b.WriteString("\n")
		}
		if len(server.Env) > 0 {
			b.WriteString("[mcp_servers.")
			b.WriteString(tomlBareKey(name))
			b.WriteString(".env]\n")
			for _, key := range sortedMapKeys(server.Env) {
				b.WriteString(tomlBareKey(key))
				b.WriteString(" = ")
				b.WriteString(tomlString(server.Env[key]))
				b.WriteString("\n")
			}
		}
	}
	return []byte(b.String())
}

func renderKiroPower(sourceSkill skill) []byte {
	if skillFile, ok := sourceSkill.Files["SKILL.md"]; ok {
		return withGeneratedHeaderAfterFrontmatter(skillFile)
	}
	return []byte("---\nname: \"" + sourceSkill.Name + "\"\ndescription: \"Generated from .ai/skills/" + sourceSkill.Name + ".\"\n---\n\n" + generatedHeader)
}

func withGeneratedHeaderAfterFrontmatter(markdown []byte) []byte {
	text := strings.ReplaceAll(string(markdown), "\r\n", "\n")
	if strings.HasPrefix(text, "---\n") {
		lines := strings.SplitAfter(text, "\n")
		for i := 1; i < len(lines); i++ {
			if strings.TrimSpace(lines[i]) == "---" {
				frontmatter := strings.Join(lines[:i+1], "")
				rest := strings.TrimLeft(strings.Join(lines[i+1:], ""), "\n")
				return []byte(frontmatter + "\n" + generatedHeader + rest)
			}
		}
	}
	return append([]byte(generatedHeader), markdown...)
}

func copySkills(skills []skill, base string, renameSkillFile bool) []generatedFile {
	var files []generatedFile
	for _, sourceSkill := range skills {
		for _, rel := range sortedFileNames(sourceSkill.Files) {
			outRel := rel
			if renameSkillFile && rel == "SKILL.md" {
				outRel = "POWER.md"
			}
			content := sourceSkill.Files[rel]
			if rel == "SKILL.md" {
				content = withGeneratedHeaderAfterFrontmatter(content)
			}
			files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(base, sourceSkill.Name, outRel)), Content: content})
		}
	}
	return files
}

func appendGeneratedManifests(outputs []generatedFile) []generatedFile {
	byDir := map[string][]string{}
	for _, output := range outputs {
		dir := skillOutputDir(output.Path)
		if dir == "" {
			continue
		}
		rel, err := filepath.Rel(filepath.FromSlash(dir), filepath.FromSlash(output.Path))
		if err != nil {
			continue
		}
		byDir[dir] = append(byDir[dir], filepath.ToSlash(rel))
	}
	for _, dir := range sortedStringMapKeys(byDir) {
		files := byDir[dir]
		sort.Strings(files)
		manifest := "# Generated by ai-sync. Do not edit directly; source is .ai/.\n" + strings.Join(files, "\n") + "\n"
		outputs = append(outputs, generatedFile{Path: filepath.ToSlash(filepath.Join(dir, ".ai-sync-manifest")), Content: []byte(manifest)})
	}
	return outputs
}

func skillOutputDir(path string) string {
	path = filepath.ToSlash(path)
	for _, root := range []string{".claude/skills", ".agents/skills", ".kiro/powers"} {
		prefix := root + "/"
		if strings.HasPrefix(path, prefix) {
			remaining := strings.TrimPrefix(path, prefix)
			name, _, ok := strings.Cut(remaining, "/")
			if ok && name != "" {
				return prefix + name
			}
		}
	}
	return ""
}

func pruneTargetOutputs(workdir string, targets []string, outputs []generatedFile, dryRun bool) ([]string, error) {
	keep := map[string]struct{}{}
	for _, output := range outputs {
		keep[filepath.ToSlash(output.Path)] = struct{}{}
	}

	var roots []string
	for _, target := range targets {
		switch target {
		case "claude":
			roots = append(roots, ".claude/skills")
		case "codex":
			roots = append(roots, ".agents/skills")
		case "kiro":
			roots = append(roots, ".kiro/powers")
		}
	}

	var changes []string
	for _, root := range roots {
		rootPath := filepath.Join(workdir, filepath.FromSlash(root))
		entries, err := os.ReadDir(rootPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read %s: %w", root, err)
		}
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			rel := filepath.ToSlash(filepath.Join(root, entry.Name()))
			if outputTreeExists(keep, rel) {
				continue
			}
			dirPath := filepath.Join(rootPath, entry.Name())
			removed, err := pruneGeneratedTree(workdir, rel, dirPath, dryRun)
			if err != nil {
				return nil, err
			}
			changes = append(changes, removed...)
		}
	}
	sort.Strings(changes)
	return changes, nil
}

func outputTreeExists(keep map[string]struct{}, root string) bool {
	prefix := strings.TrimSuffix(root, "/") + "/"
	for path := range keep {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}
	return false
}

func pruneGeneratedTree(workdir, relRoot, dirPath string, dryRun bool) ([]string, error) {
	manifestPath := filepath.Join(dirPath, ".ai-sync-manifest")
	manifest, err := os.ReadFile(manifestPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", filepath.ToSlash(strings.TrimPrefix(manifestPath, workdir+string(os.PathSeparator))), err)
	}
	if !bytes.HasPrefix(manifest, []byte("# Generated by ai-sync.")) {
		return nil, nil
	}

	var changes []string
	for _, generatedRel := range strings.Split(string(manifest), "\n") {
		generatedRel = strings.TrimSpace(generatedRel)
		if generatedRel == "" || strings.HasPrefix(generatedRel, "#") {
			continue
		}
		if !safeRelativePath(generatedRel) {
			continue
		}
		fullPath := filepath.Join(dirPath, filepath.FromSlash(generatedRel))
		if _, err := os.Stat(fullPath); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("stat %s/%s: %w", relRoot, generatedRel, err)
		}
		verb := "removed"
		if dryRun {
			verb = "would remove"
		} else if err := os.Remove(fullPath); err != nil {
			return nil, fmt.Errorf("remove %s/%s: %w", relRoot, generatedRel, err)
		}
		changes = append(changes, verb+" "+relRoot+"/"+generatedRel)
	}

	if dryRun {
		changes = append(changes, "would remove "+relRoot+"/.ai-sync-manifest")
		return changes, nil
	}
	if err := os.Remove(manifestPath); err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("remove %s/.ai-sync-manifest: %w", relRoot, err)
	}
	removeEmptyParents(dirPath)
	return changes, nil
}

func safeRelativePath(path string) bool {
	if path == "" || strings.HasPrefix(path, "/") || strings.Contains(path, "\\") {
		return false
	}
	clean := filepath.ToSlash(filepath.Clean(filepath.FromSlash(path)))
	return clean == path && path != "." && !strings.HasPrefix(path, "../") && path != ".."
}

func removeEmptyParents(path string) {
	for {
		if err := os.Remove(path); err != nil {
			return
		}
		parent := filepath.Dir(path)
		if parent == path || filepath.Base(parent) == ".claude" || filepath.Base(parent) == ".agents" || filepath.Base(parent) == ".kiro" {
			return
		}
		path = parent
	}
}

func applyOutputs(workdir string, outputs []generatedFile, dryRun bool) ([]string, error) {
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].Path < outputs[j].Path })
	var changes []string
	for _, output := range outputs {
		path := filepath.Join(workdir, filepath.FromSlash(output.Path))
		current, err := os.ReadFile(path)
		if err == nil && bytes.Equal(current, output.Content) {
			continue
		}
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("read %s: %w", output.Path, err)
		}
		verb := "wrote"
		if dryRun {
			verb = "would write"
		} else {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return nil, fmt.Errorf("mkdir %s: %w", filepath.ToSlash(filepath.Dir(path)), err)
			}
			if err := os.WriteFile(path, output.Content, 0o644); err != nil {
				return nil, fmt.Errorf("write %s: %w", output.Path, err)
			}
		}
		changes = append(changes, verb+" "+output.Path)
	}
	return changes, nil
}

func mustJSON(value any) []byte {
	contents, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(contents, '\n')
}

func mcpServersJSON(mcp mcpConfig) map[string]any {
	servers := map[string]any{}
	for _, name := range sortedServerNames(mcp.Servers) {
		server := mcp.Servers[name]
		entry := map[string]any{"command": server.Command}
		if len(server.Args) > 0 {
			entry["args"] = server.Args
		}
		if len(server.Env) > 0 {
			entry["env"] = server.Env
		}
		servers[name] = entry
	}
	return servers
}

func sortedServerNames(servers map[string]mcpServer) []string {
	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedFileNames(files map[string][]byte) []string {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedStringMapKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedMapKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func tomlString(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(encoded)
}

func tomlStringArray(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, tomlString(value))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func tomlBareKey(value string) string {
	if value == "" {
		return tomlString(value)
	}
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			continue
		}
		return tomlString(value)
	}
	return value
}
