package app

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatedHeader = "<!-- Generated by ai-sync. Do not edit directly; source is .ai/. -->\n\n"

var allTargets = []string{"claude", "codex", "kiro"}

// BuildInfo describes the binary version metadata shown by the version command.
type BuildInfo struct {
	Version string
	Commit  string
	Date    string
}

// Run executes ai-sync in workdir with CLI-style args and returns user-facing output.
func Run(workdir string, args []string) (string, error) {
	return RunWithBuildInfo(workdir, args, BuildInfo{Version: "dev", Commit: "unknown", Date: "unknown"})
}

// RunWithBuildInfo executes ai-sync with explicit build metadata.
func RunWithBuildInfo(workdir string, args []string, build BuildInfo) (string, error) {
	if len(args) > 0 && args[0] == "init" {
		return initSource(workdir)
	}
	if len(args) > 0 && args[0] == "convention" {
		return conventionText(), nil
	}
	if len(args) > 0 && args[0] == "list" {
		return listGeneratedFiles(workdir, args[1:])
	}
	if wantsVersion(args) {
		return versionText(build), nil
	}
	if wantsHelp(args) {
		return helpText(), nil
	}

	var opts options
	flags := flag.NewFlagSet("ai-sync", flag.ContinueOnError)
	var flagOutput bytes.Buffer
	flags.SetOutput(&flagOutput)
	flags.StringVar(&opts.target, "target", "", "target to generate: claude, codex, or kiro")
	flags.BoolVar(&opts.dryRun, "dry-run", false, "show changes without writing")
	if err := flags.Parse(args); err != nil {
		output := flagOutput.String()
		if errors.Is(err, flag.ErrHelp) {
			return output, nil
		}
		return strings.TrimSpace(output), err
	}
	if flags.NArg() > 0 {
		return "", fmt.Errorf("unknown command %q", flags.Arg(0))
	}

	outputs, err := renderOutputs(workdir, opts.target)
	if err != nil {
		return "", err
	}

	targets, err := selectedTargets(opts.target)
	if err != nil {
		return "", err
	}

	changes, err := pruneTargetOutputs(workdir, targets, outputs, opts.dryRun)
	if err != nil {
		return "", err
	}
	written, err := applyOutputs(workdir, outputs, opts.dryRun)
	if err != nil {
		return "", err
	}
	changes = append(changes, written...)
	if len(changes) == 0 {
		return "no changes\n", nil
	}
	return strings.Join(changes, "\n") + "\n", nil
}

func listGeneratedFiles(workdir string, args []string) (string, error) {
	var opts options
	flags := flag.NewFlagSet("ai-sync list", flag.ContinueOnError)
	var flagOutput bytes.Buffer
	flags.SetOutput(&flagOutput)
	flags.StringVar(&opts.target, "target", "", "target to list: claude, codex, or kiro")
	if err := flags.Parse(args); err != nil {
		output := flagOutput.String()
		if errors.Is(err, flag.ErrHelp) {
			return output, nil
		}
		return strings.TrimSpace(output), err
	}
	if flags.NArg() > 0 {
		return "", fmt.Errorf("unknown list argument %q", flags.Arg(0))
	}

	outputs, err := renderOutputs(workdir, opts.target)
	if err != nil {
		return "", err
	}
	paths := make([]string, 0, len(outputs))
	for _, output := range outputs {
		paths = append(paths, filepath.ToSlash(output.Path))
	}
	sort.Strings(paths)
	return strings.Join(paths, "\n") + "\n", nil
}

func wantsVersion(args []string) bool {
	for _, arg := range args {
		if arg == "version" || arg == "--version" || arg == "-v" {
			return true
		}
	}
	return false
}

func wantsHelp(args []string) bool {
	for _, arg := range args {
		if arg == "--help" || arg == "-h" {
			return true
		}
	}
	return false
}

func helpText() string {
	return `ai-sync keeps AI-agent configuration in one canonical .ai/ directory.

Usage:
  ai-sync [--target claude|codex|kiro] [--dry-run]
  ai-sync init
  ai-sync convention
  ai-sync list
  ai-sync version

Commands:
  init              scaffold a starter .ai/ directory
  convention        print the .ai authoring convention for humans or AI agents
  list              print generated file paths without writing files
  version           print version and build metadata

Options:
  --target string   target to generate: claude, codex, or kiro
  --dry-run         show changes without writing
  --version, -v     print version and build metadata
  --help, -h        show help

Examples:
  ai-sync init
  ai-sync convention
  ai-sync list
  ai-sync version
  ai-sync
  ai-sync --target codex
  ai-sync --dry-run

See README.md for the .ai authoring standard.
`
}

func versionText(build BuildInfo) string {
	return fmt.Sprintf("ai-sync %s\ncommit %s\nbuilt %s\n", build.Version, build.Commit, build.Date)
}

func conventionText() string {
	return `# ai-sync .ai Authoring Convention

Create a canonical .ai/ directory for the project. ai-sync reads this directory and generates the agent-specific files for Claude Code, Codex, and Kiro.

## Goal

Use .ai/ as the single source of truth for AI-agent configuration. Do not create generated agent files directly, such as CLAUDE.md, AGENTS.md, .mcp.json, .codex/config.toml, or .kiro/settings/mcp.json.

## Required structure

` + "```txt" + `
.ai/
  project.md
  mcp.yaml
  targets/
    claude.md
    codex.md
    kiro.md
  rules/
    <name>.md
  skills/
    <name>/
      SKILL.md
      scripts/
      references/
      assets/
` + "```" + `

## Files

| File | Purpose |
| --- | --- |
| .ai/project.md | Shared project rules, architecture, commands, conventions, and review expectations. |
| .ai/mcp.yaml | Shared MCP server definitions. Reference environment variables instead of hardcoding secrets. |
| .ai/targets/claude.md | Claude Code-specific guidance only. |
| .ai/targets/codex.md | Codex-specific guidance only. |
| .ai/targets/kiro.md | Kiro-specific guidance only. |
| .ai/rules/<name>.md | Path-scoped rules with a YAML frontmatter paths list and Markdown guidance. |
| .ai/skills/<name>/SKILL.md | Reusable workflow instructions copied into each agent's expected skill format. |

## Authoring rules

- Put shared guidance in .ai/project.md.
- Put agent-specific overrides in .ai/targets/<target>.md.
- Put path-scoped guidance in .ai/rules/<name>.md with a paths list in YAML frontmatter. ai-sync maps these rules to native Claude Code .claude/rules files, native Kiro fileMatch steering files, and nested Codex AGENTS.md files.
- Put reusable workflows in .ai/skills/<name>/SKILL.md.
- Keep secrets out of .ai/mcp.yaml; use environment variables.
- Do not create generated agent files directly. Run ai-sync after creating or editing .ai/.

## Suggested prompt for an AI agent

Create the .ai/ directory using the ai-sync convention. Add shared project guidance to .ai/project.md, define MCP servers in .ai/mcp.yaml, put agent-specific instructions under .ai/targets/, add path-scoped guidance under .ai/rules/<name>.md, and add reusable workflows under .ai/skills/<name>/SKILL.md. Do not create CLAUDE.md, AGENTS.md, .codex/config.toml, .mcp.json, or .kiro/settings/mcp.json directly.
`
}

type options struct {
	target string
	dryRun bool
}

type source struct {
	Project string
	Targets map[string]string
	Rules   []pathRule
	MCP     mcpConfig
	Skills  []skill
}

type mcpConfig struct {
	Servers map[string]mcpServer `yaml:"servers"`
}

type mcpServer struct {
	Command string            `yaml:"command"`
	Args    []string          `yaml:"args"`
	Env     map[string]string `yaml:"env"`
}

type pathRule struct {
	Name    string
	Paths   []string
	Content string
}

type ruleFrontmatter struct {
	Paths []string `yaml:"paths"`
}

type skill struct {
	Name  string
	Files map[string][]byte
}

type generatedFile struct {
	Path    string
	Content []byte
}

func initSource(workdir string) (string, error) {
	files := []generatedFile{
		{Path: ".ai/project.md", Content: []byte("# Project\n\nDescribe shared stack, commands, conventions, and review expectations here.\n")},
		{Path: ".ai/mcp.yaml", Content: []byte("servers: {}\n")},
		{Path: ".ai/targets/claude.md", Content: []byte("# Claude Code\n\nAdd Claude-specific guidance here.\n")},
		{Path: ".ai/targets/codex.md", Content: []byte("# Codex\n\nAdd Codex-specific guidance here.\n")},
		{Path: ".ai/targets/kiro.md", Content: []byte("# Kiro\n\nAdd Kiro-specific guidance here.\n")},
		{Path: ".ai/rules/example.md", Content: []byte("---\npaths:\n  - \"src/**\"\n---\n\n# Example Path Rules\n\nAdd guidance that applies only to matching paths.\n")},
		{Path: ".ai/skills/example/SKILL.md", Content: []byte("---\nname: \"example\"\ndescription: \"Explain when this reusable workflow should be used.\"\n---\n\n# Example Skill\n\nDocument the workflow here.\n")},
	}
	changes, err := applyOutputs(workdir, files, false)
	if err != nil {
		return "", err
	}
	if len(changes) == 0 {
		return ".ai already exists\n", nil
	}
	return "created .ai\n" + strings.Join(changes, "\n") + "\n", nil
}

func loadSource(workdir string) (source, error) {
	root := filepath.Join(workdir, ".ai")
	if _, err := os.Stat(root); err != nil {
		if os.IsNotExist(err) {
			return source{}, errors.New("canonical source .ai/ not found; run `ai-sync init` first")
		}
		return source{}, err
	}

	project, err := readRequiredText(filepath.Join(root, "project.md"))
	if err != nil {
		return source{}, err
	}

	mcpBytes, err := os.ReadFile(filepath.Join(root, "mcp.yaml"))
	if err != nil {
		return source{}, fmt.Errorf("read .ai/mcp.yaml: %w", err)
	}
	var mcp mcpConfig
	if err := yaml.Unmarshal(mcpBytes, &mcp); err != nil {
		return source{}, fmt.Errorf("parse .ai/mcp.yaml: %w", err)
	}
	if mcp.Servers == nil {
		mcp.Servers = map[string]mcpServer{}
	}

	targets := make(map[string]string, len(allTargets))
	for _, target := range allTargets {
		path := filepath.Join(root, "targets", target+".md")
		text, err := readOptionalText(path)
		if err != nil {
			return source{}, err
		}
		targets[target] = text
	}

	rules, err := loadPathRules(filepath.Join(root, "rules"))
	if err != nil {
		return source{}, err
	}

	skills, err := loadSkills(filepath.Join(root, "skills"))
	if err != nil {
		return source{}, err
	}

	return source{Project: project, Targets: targets, Rules: rules, MCP: mcp, Skills: skills}, nil
}

func readRequiredText(path string) (string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", filepath.ToSlash(path), err)
	}
	return normalizeMarkdown(string(contents)), nil
}

func readOptionalText(path string) (string, error) {
	contents, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return "", nil
		}
		return "", fmt.Errorf("read %s: %w", filepath.ToSlash(path), err)
	}
	return normalizeMarkdown(string(contents)), nil
}

func normalizeMarkdown(text string) string {
	return strings.TrimSpace(strings.ReplaceAll(text, "\r\n", "\n")) + "\n"
}

func loadPathRules(root string) ([]pathRule, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .ai/rules: %w", err)
	}

	var rules []pathRule
	for _, entry := range entries {
		if entry.IsDir() || strings.HasPrefix(entry.Name(), ".") || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		path := filepath.Join(root, entry.Name())
		contents, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("read .ai/rules/%s: %w", entry.Name(), err)
		}
		rule, err := parsePathRule(strings.TrimSuffix(entry.Name(), ".md"), contents)
		if err != nil {
			return nil, fmt.Errorf("parse .ai/rules/%s: %w", entry.Name(), err)
		}
		rules = append(rules, rule)
	}
	sort.Slice(rules, func(i, j int) bool { return rules[i].Name < rules[j].Name })
	return rules, nil
}

func parsePathRule(name string, contents []byte) (pathRule, error) {
	text := strings.ReplaceAll(string(contents), "\r\n", "\n")
	if !strings.HasPrefix(text, "---\n") {
		return pathRule{}, errors.New("missing YAML frontmatter with paths")
	}

	frontmatter, body, ok := splitYAMLFrontmatter(text)
	if !ok {
		return pathRule{}, errors.New("missing closing frontmatter delimiter")
	}

	var meta ruleFrontmatter
	if err := yaml.Unmarshal([]byte(frontmatter), &meta); err != nil {
		return pathRule{}, err
	}
	if len(meta.Paths) == 0 {
		return pathRule{}, errors.New("paths must contain at least one glob")
	}
	for _, path := range meta.Paths {
		if strings.TrimSpace(path) == "" {
			return pathRule{}, errors.New("paths cannot contain empty globs")
		}
	}

	return pathRule{Name: name, Paths: meta.Paths, Content: normalizeMarkdown(body)}, nil
}

func splitYAMLFrontmatter(text string) (string, string, bool) {
	lines := strings.SplitAfter(text[len("---\n"):], "\n")
	var frontmatter strings.Builder
	for i, line := range lines {
		if strings.TrimSpace(line) == "---" {
			body := strings.Join(lines[i+1:], "")
			return frontmatter.String(), strings.TrimLeft(body, "\n"), true
		}
		frontmatter.WriteString(line)
	}
	return "", "", false
}

func loadSkills(root string) ([]skill, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read .ai/skills: %w", err)
	}

	var skills []skill
	for _, entry := range entries {
		if !entry.IsDir() || strings.HasPrefix(entry.Name(), ".") {
			continue
		}
		name := entry.Name()
		files := map[string][]byte{}
		skillRoot := filepath.Join(root, name)
		if err := filepath.WalkDir(skillRoot, func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				return nil
			}
			rel, err := filepath.Rel(skillRoot, path)
			if err != nil {
				return err
			}
			contents, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			files[filepath.ToSlash(rel)] = contents
			return nil
		}); err != nil {
			return nil, fmt.Errorf("read skill %s: %w", name, err)
		}
		skills = append(skills, skill{Name: name, Files: files})
	}
	sort.Slice(skills, func(i, j int) bool { return skills[i].Name < skills[j].Name })
	return skills, nil
}

func selectedTargets(target string) ([]string, error) {
	if target == "" {
		return append([]string(nil), allTargets...), nil
	}
	for _, known := range allTargets {
		if target == known {
			return []string{target}, nil
		}
	}
	return nil, fmt.Errorf("unknown target %q; expected claude, codex, or kiro", target)
}

func renderOutputs(workdir, target string) ([]generatedFile, error) {
	source, err := loadSource(workdir)
	if err != nil {
		return nil, err
	}

	targets, err := selectedTargets(target)
	if err != nil {
		return nil, err
	}

	var outputs []generatedFile
	for _, target := range targets {
		targetOutputs, err := renderTarget(target, source)
		if err != nil {
			return nil, err
		}
		outputs = append(outputs, targetOutputs...)
	}
	return appendGeneratedManifests(outputs), nil
}

func renderTarget(target string, source source) ([]generatedFile, error) {
	switch target {
	case "claude":
		return renderClaude(source)
	case "codex":
		return renderCodex(source)
	case "kiro":
		return renderKiro(source)
	default:
		return nil, fmt.Errorf("unknown target %q", target)
	}
}

func renderClaude(source source) ([]generatedFile, error) {
	files := []generatedFile{
		{Path: "CLAUDE.md", Content: renderGuidance("Claude Code", source.Project, source.Targets["claude"], nil)},
		{Path: ".claude/settings.json", Content: mustJSON(map[string]any{"permissions": map[string]any{}})},
		{Path: ".mcp.json", Content: mustJSON(map[string]any{"mcpServers": mcpServersJSON(source.MCP)})},
	}
	for _, rule := range source.Rules {
		files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(".claude/rules", rule.Name+".md")), Content: renderClaudeRule(rule)})
	}
	files = append(files, copySkills(source.Skills, ".claude/skills", false)...)
	return files, nil
}

func renderClaudeRule(rule pathRule) []byte {
	var b strings.Builder
	b.WriteString("---\npaths:\n")
	for _, path := range rule.Paths {
		b.WriteString("  - ")
		b.WriteString(strconv.Quote(path))
		b.WriteString("\n")
	}
	b.WriteString("---\n\n")
	b.WriteString(generatedHeader)
	b.WriteString(renderPathScopeNotice(rule.Paths))
	b.WriteString(strings.TrimSpace(rule.Content))
	b.WriteString("\n")
	return []byte(b.String())
}

func renderCodex(source source) ([]generatedFile, error) {
	rootRules, scopedFiles := renderCodexScopedAgents(source.Rules)
	files := []generatedFile{
		{Path: "AGENTS.md", Content: renderGuidance("Codex", source.Project, source.Targets["codex"], rootRules)},
		{Path: ".codex/config.toml", Content: renderCodexConfig(source.MCP)},
	}
	files = append(files, scopedFiles...)
	if len(scopedFiles) > 0 {
		files = append(files, generatedFile{Path: ".codex/scoped-agents-manifest", Content: renderCodexScopedAgentsManifest(scopedFiles)})
	}
	files = append(files, copySkills(source.Skills, ".agents/skills", false)...)
	return files, nil
}

func renderCodexScopedAgents(rules []pathRule) ([]pathRule, []generatedFile) {
	rulesByDir := map[string][]pathRule{}
	var rootRules []pathRule

	for _, rule := range rules {
		dirsForRule := map[string]struct{}{}
		for _, pattern := range rule.Paths {
			dir := codexScopeDir(pattern)
			dirsForRule[dir] = struct{}{}
		}
		for _, dir := range sortedStringMapKeys(dirsForRule) {
			if dir == "" {
				rootRules = append(rootRules, rule)
				continue
			}
			rulesByDir[dir] = append(rulesByDir[dir], rule)
		}
	}

	var files []generatedFile
	for _, dir := range sortedStringMapKeys(rulesByDir) {
		files = append(files, generatedFile{
			Path:    filepath.ToSlash(filepath.Join(dir, "AGENTS.md")),
			Content: renderCodexScopedGuidance(rulesByDir[dir]),
		})
	}
	return rootRules, files
}

func codexScopeDir(pattern string) string {
	pattern = filepath.ToSlash(strings.TrimSpace(pattern))
	pattern = strings.TrimPrefix(pattern, "./")
	if pattern == "" || strings.HasPrefix(pattern, "/") || strings.HasPrefix(pattern, "../") || pattern == ".." {
		return ""
	}

	parts := strings.Split(pattern, "/")
	baseParts := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" || strings.ContainsAny(part, "*?[") || strings.Contains(part, "{") {
			break
		}
		baseParts = append(baseParts, part)
	}
	if len(baseParts) == 0 {
		return ""
	}
	if len(baseParts) == len(parts) {
		baseParts = baseParts[:len(baseParts)-1]
	}
	if len(baseParts) == 0 {
		return ""
	}
	return filepath.ToSlash(filepath.Clean(filepath.Join(baseParts...)))
}

func renderCodexScopedGuidance(rules []pathRule) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# Codex Path-Scoped Agent Instructions\n")
	b.WriteString("\n## Scope\n\n")
	b.WriteString("This AGENTS.md applies only to files in this directory tree. Apply each rule below only to files matching its listed globs.\n")
	for _, rule := range rules {
		b.WriteString("\n### ")
		b.WriteString(rule.Name)
		b.WriteString("\n\n")
		b.WriteString("Applies to: ")
		b.WriteString(formatInlineCodeList(rule.Paths))
		b.WriteString("\n\n")
		b.WriteString(strings.TrimSpace(rule.Content))
		b.WriteString("\n")
	}
	return []byte(b.String())
}

func renderCodexScopedAgentsManifest(files []generatedFile) []byte {
	paths := make([]string, 0, len(files))
	for _, file := range files {
		paths = append(paths, filepath.ToSlash(file.Path))
	}
	sort.Strings(paths)
	return []byte("# Generated by ai-sync. Do not edit directly; source is .ai/.\n" + strings.Join(paths, "\n") + "\n")
}

func renderKiro(source source) ([]generatedFile, error) {
	files := []generatedFile{
		{Path: ".kiro/steering/project-conventions.md", Content: renderGuidance("Kiro", source.Project, source.Targets["kiro"], nil)},
		{Path: ".kiro/settings/mcp.json", Content: mustJSON(map[string]any{"mcpServers": mcpServersJSON(source.MCP)})},
	}
	for _, rule := range source.Rules {
		files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(".kiro/steering", rule.Name+".md")), Content: renderKiroSteeringRule(rule)})
	}
	for _, sourceSkill := range source.Skills {
		files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(".kiro/powers", sourceSkill.Name, "POWER.md")), Content: renderKiroPower(sourceSkill)})
		for _, rel := range sortedFileNames(sourceSkill.Files) {
			if rel == "SKILL.md" {
				continue
			}
			files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(".kiro/powers", sourceSkill.Name, rel)), Content: sourceSkill.Files[rel]})
		}
	}
	files = append(files, copySkills(source.Skills, ".kiro/skills", false)...)
	return files, nil
}

func renderKiroSteeringRule(rule pathRule) []byte {
	var b strings.Builder
	b.WriteString("---\ninclusion: fileMatch\nfileMatchPattern: [")
	for i, path := range rule.Paths {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(strconv.Quote(path))
	}
	b.WriteString("]\n---\n\n")
	b.WriteString(generatedHeader)
	b.WriteString(renderPathScopeNotice(rule.Paths))
	b.WriteString(strings.TrimSpace(rule.Content))
	b.WriteString("\n")
	return []byte(b.String())
}

func renderGuidance(target, project, override string, rules []pathRule) []byte {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("# ")
	b.WriteString(target)
	b.WriteString(" Agent Instructions\n\n")
	b.WriteString("## Shared Project Guidance\n\n")
	b.WriteString(strings.TrimSpace(project))
	b.WriteString("\n")
	if strings.TrimSpace(override) != "" {
		b.WriteString("\n## Target-Specific Guidance\n\n")
		b.WriteString(strings.TrimSpace(override))
		b.WriteString("\n")
	}
	if len(rules) > 0 {
		b.WriteString("\n## Path-Scoped Rules\n")
		b.WriteString("\n## Scope\n\n")
		b.WriteString("The rules below are path-scoped. Apply each rule only to files matching its listed globs.\n")
		for _, rule := range rules {
			b.WriteString("\n### ")
			b.WriteString(rule.Name)
			b.WriteString("\n\n")
			b.WriteString("Applies to: ")
			b.WriteString(formatInlineCodeList(rule.Paths))
			b.WriteString("\n\n")
			b.WriteString(strings.TrimSpace(rule.Content))
			b.WriteString("\n")
		}
	}
	return []byte(b.String())
}

func renderPathScopeNotice(paths []string) string {
	return "## Scope\n\nThese rules are path-scoped. Apply the instructions below only to files matching: " + formatInlineCodeList(paths) + ".\n\n"
}

func formatInlineCodeList(values []string) string {
	quoted := make([]string, 0, len(values))
	for _, value := range values {
		quoted = append(quoted, "`"+value+"`")
	}
	return strings.Join(quoted, ", ")
}

func renderCodexConfig(mcp mcpConfig) []byte {
	var b strings.Builder
	b.WriteString("# Generated by ai-sync. Do not edit directly; source is .ai/.\n")
	for _, name := range sortedServerNames(mcp.Servers) {
		server := mcp.Servers[name]
		b.WriteString("\n[mcp_servers.")
		b.WriteString(tomlBareKey(name))
		b.WriteString("]\n")
		b.WriteString("command = ")
		b.WriteString(tomlString(server.Command))
		b.WriteString("\n")
		if len(server.Args) > 0 {
			b.WriteString("args = ")
			b.WriteString(tomlStringArray(server.Args))
			b.WriteString("\n")
		}
		if len(server.Env) > 0 {
			b.WriteString("[mcp_servers.")
			b.WriteString(tomlBareKey(name))
			b.WriteString(".env]\n")
			for _, key := range sortedMapKeys(server.Env) {
				b.WriteString(tomlBareKey(key))
				b.WriteString(" = ")
				b.WriteString(tomlString(server.Env[key]))
				b.WriteString("\n")
			}
		}
	}
	return []byte(b.String())
}

func renderKiroPower(sourceSkill skill) []byte {
	if skillFile, ok := sourceSkill.Files["SKILL.md"]; ok {
		return withGeneratedHeaderAfterFrontmatter(skillFile)
	}
	return []byte("---\nname: \"" + sourceSkill.Name + "\"\ndescription: \"Generated from .ai/skills/" + sourceSkill.Name + ".\"\n---\n\n" + generatedHeader)
}

func withGeneratedHeaderAfterFrontmatter(markdown []byte) []byte {
	text := strings.ReplaceAll(string(markdown), "\r\n", "\n")
	if strings.HasPrefix(text, "---\n") {
		lines := strings.SplitAfter(text, "\n")
		for i := 1; i < len(lines); i++ {
			if strings.TrimSpace(lines[i]) == "---" {
				frontmatter := strings.Join(lines[:i+1], "")
				rest := strings.TrimLeft(strings.Join(lines[i+1:], ""), "\n")
				return []byte(frontmatter + "\n" + generatedHeader + rest)
			}
		}
	}
	return append([]byte(generatedHeader), markdown...)
}

func copySkills(skills []skill, base string, renameSkillFile bool) []generatedFile {
	var files []generatedFile
	for _, sourceSkill := range skills {
		for _, rel := range sortedFileNames(sourceSkill.Files) {
			outRel := rel
			if renameSkillFile && rel == "SKILL.md" {
				outRel = "POWER.md"
			}
			content := sourceSkill.Files[rel]
			if rel == "SKILL.md" {
				content = withGeneratedHeaderAfterFrontmatter(content)
			}
			files = append(files, generatedFile{Path: filepath.ToSlash(filepath.Join(base, sourceSkill.Name, outRel)), Content: content})
		}
	}
	return files
}

func appendGeneratedManifests(outputs []generatedFile) []generatedFile {
	byDir := map[string][]string{}
	for _, output := range outputs {
		dir := manifestOutputDir(output.Path)
		if dir == "" {
			continue
		}
		rel, err := filepath.Rel(filepath.FromSlash(dir), filepath.FromSlash(output.Path))
		if err != nil {
			continue
		}
		byDir[dir] = append(byDir[dir], filepath.ToSlash(rel))
	}
	for _, dir := range sortedStringMapKeys(byDir) {
		files := byDir[dir]
		sort.Strings(files)
		manifest := "# Generated by ai-sync. Do not edit directly; source is .ai/.\n" + strings.Join(files, "\n") + "\n"
		outputs = append(outputs, generatedFile{Path: filepath.ToSlash(filepath.Join(dir, ".ai-sync-manifest")), Content: []byte(manifest)})
	}
	return outputs
}

func manifestOutputDir(path string) string {
	path = filepath.ToSlash(path)
	for _, dir := range []string{".claude/rules", ".kiro/steering"} {
		if strings.HasPrefix(path, dir+"/") {
			return dir
		}
	}
	for _, root := range []string{".claude/skills", ".agents/skills", ".kiro/powers", ".kiro/skills"} {
		prefix := root + "/"
		if strings.HasPrefix(path, prefix) {
			remaining := strings.TrimPrefix(path, prefix)
			name, _, ok := strings.Cut(remaining, "/")
			if ok && name != "" {
				return prefix + name
			}
		}
	}
	return ""
}

func pruneTargetOutputs(workdir string, targets []string, outputs []generatedFile, dryRun bool) ([]string, error) {
	keep := map[string]struct{}{}
	for _, output := range outputs {
		keep[filepath.ToSlash(output.Path)] = struct{}{}
	}

	var roots []string
	var manifestDirs []string
	for _, target := range targets {
		switch target {
		case "claude":
			roots = append(roots, ".claude/skills")
			manifestDirs = append(manifestDirs, ".claude/rules")
		case "codex":
			roots = append(roots, ".agents/skills")
		case "kiro":
			roots = append(roots, ".kiro/powers", ".kiro/skills")
			manifestDirs = append(manifestDirs, ".kiro/steering")
		}
	}

	var changes []string
	for _, root := range roots {
		rootPath := filepath.Join(workdir, filepath.FromSlash(root))
		entries, err := os.ReadDir(rootPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read %s: %w", root, err)
		}
		for _, entry := range entries {
			if !entry.IsDir() {
				continue
			}
			rel := filepath.ToSlash(filepath.Join(root, entry.Name()))
			if outputTreeExists(keep, rel) {
				continue
			}
			dirPath := filepath.Join(rootPath, entry.Name())
			removed, err := pruneGeneratedTree(workdir, rel, dirPath, dryRun)
			if err != nil {
				return nil, err
			}
			changes = append(changes, removed...)
		}
	}
	if targetSelected(targets, "codex") {
		removed, err := pruneCodexScopedAgents(workdir, keep, dryRun)
		if err != nil {
			return nil, err
		}
		changes = append(changes, removed...)
	}
	for _, dir := range manifestDirs {
		removed, err := pruneGeneratedFilesInDir(workdir, dir, keep, dryRun)
		if err != nil {
			return nil, err
		}
		changes = append(changes, removed...)
	}
	sort.Strings(changes)
	return changes, nil
}

func targetSelected(targets []string, want string) bool {
	for _, target := range targets {
		if target == want {
			return true
		}
	}
	return false
}

func pruneCodexScopedAgents(workdir string, keep map[string]struct{}, dryRun bool) ([]string, error) {
	manifestRel := ".codex/scoped-agents-manifest"
	manifestPath := filepath.Join(workdir, filepath.FromSlash(manifestRel))
	manifest, err := os.ReadFile(manifestPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", manifestRel, err)
	}
	if !bytes.HasPrefix(manifest, []byte("# Generated by ai-sync.")) {
		return nil, nil
	}

	var changes []string
	for _, generatedRel := range strings.Split(string(manifest), "\n") {
		generatedRel = strings.TrimSpace(generatedRel)
		if generatedRel == "" || strings.HasPrefix(generatedRel, "#") {
			continue
		}
		if !safeRelativePath(generatedRel) {
			continue
		}
		if _, ok := keep[generatedRel]; ok {
			continue
		}
		fullPath := filepath.Join(workdir, filepath.FromSlash(generatedRel))
		contents, err := os.ReadFile(fullPath)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read %s: %w", generatedRel, err)
		}
		if !hasGeneratedMarker(contents) {
			continue
		}
		verb := "removed"
		if dryRun {
			verb = "would remove"
		} else if err := os.Remove(fullPath); err != nil {
			return nil, fmt.Errorf("remove %s: %w", generatedRel, err)
		}
		changes = append(changes, verb+" "+generatedRel)
		if !dryRun {
			removeEmptyParents(filepath.Dir(fullPath))
		}
	}
	if _, ok := keep[manifestRel]; !ok {
		verb := "removed"
		if dryRun {
			verb = "would remove"
		} else if err := os.Remove(manifestPath); err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("remove %s: %w", manifestRel, err)
		}
		changes = append(changes, verb+" "+manifestRel)
	}
	return changes, nil
}

func pruneGeneratedFilesInDir(workdir, relDir string, keep map[string]struct{}, dryRun bool) ([]string, error) {
	dirPath := filepath.Join(workdir, filepath.FromSlash(relDir))
	manifestPath := filepath.Join(dirPath, ".ai-sync-manifest")
	manifest, err := os.ReadFile(manifestPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s/.ai-sync-manifest: %w", relDir, err)
	}
	if !bytes.HasPrefix(manifest, []byte("# Generated by ai-sync.")) {
		return nil, nil
	}

	var changes []string
	for _, generatedRel := range strings.Split(string(manifest), "\n") {
		generatedRel = strings.TrimSpace(generatedRel)
		if generatedRel == "" || strings.HasPrefix(generatedRel, "#") {
			continue
		}
		if !safeRelativePath(generatedRel) {
			continue
		}
		relPath := filepath.ToSlash(filepath.Join(relDir, generatedRel))
		if _, ok := keep[relPath]; ok {
			continue
		}
		fullPath := filepath.Join(dirPath, filepath.FromSlash(generatedRel))
		if _, err := os.Stat(fullPath); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("stat %s: %w", relPath, err)
		}
		verb := "removed"
		if dryRun {
			verb = "would remove"
		} else if err := os.Remove(fullPath); err != nil {
			return nil, fmt.Errorf("remove %s: %w", relPath, err)
		}
		changes = append(changes, verb+" "+relPath)
	}
	if !outputTreeExists(keep, relDir) {
		manifestRel := filepath.ToSlash(filepath.Join(relDir, ".ai-sync-manifest"))
		verb := "removed"
		if dryRun {
			verb = "would remove"
		} else if err := os.Remove(manifestPath); err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("remove %s: %w", manifestRel, err)
		}
		changes = append(changes, verb+" "+manifestRel)
		if !dryRun {
			removeEmptyParents(dirPath)
		}
	}
	return changes, nil
}

func outputTreeExists(keep map[string]struct{}, root string) bool {
	prefix := strings.TrimSuffix(root, "/") + "/"
	for path := range keep {
		if strings.HasPrefix(path, prefix) {
			return true
		}
	}
	return false
}

func pruneGeneratedTree(workdir, relRoot, dirPath string, dryRun bool) ([]string, error) {
	manifestPath := filepath.Join(dirPath, ".ai-sync-manifest")
	manifest, err := os.ReadFile(manifestPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("read %s: %w", filepath.ToSlash(strings.TrimPrefix(manifestPath, workdir+string(os.PathSeparator))), err)
	}
	if !bytes.HasPrefix(manifest, []byte("# Generated by ai-sync.")) {
		return nil, nil
	}

	var changes []string
	for _, generatedRel := range strings.Split(string(manifest), "\n") {
		generatedRel = strings.TrimSpace(generatedRel)
		if generatedRel == "" || strings.HasPrefix(generatedRel, "#") {
			continue
		}
		if !safeRelativePath(generatedRel) {
			continue
		}
		fullPath := filepath.Join(dirPath, filepath.FromSlash(generatedRel))
		if _, err := os.Stat(fullPath); err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("stat %s/%s: %w", relRoot, generatedRel, err)
		}
		verb := "removed"
		if dryRun {
			verb = "would remove"
		} else if err := os.Remove(fullPath); err != nil {
			return nil, fmt.Errorf("remove %s/%s: %w", relRoot, generatedRel, err)
		}
		changes = append(changes, verb+" "+relRoot+"/"+generatedRel)
	}

	if dryRun {
		changes = append(changes, "would remove "+relRoot+"/.ai-sync-manifest")
		return changes, nil
	}
	if err := os.Remove(manifestPath); err != nil && !os.IsNotExist(err) {
		return nil, fmt.Errorf("remove %s/.ai-sync-manifest: %w", relRoot, err)
	}
	removeEmptyParents(dirPath)
	return changes, nil
}

func safeRelativePath(path string) bool {
	if path == "" || strings.HasPrefix(path, "/") || strings.Contains(path, "\\") {
		return false
	}
	clean := filepath.ToSlash(filepath.Clean(filepath.FromSlash(path)))
	return clean == path && path != "." && !strings.HasPrefix(path, "../") && path != ".."
}

func removeEmptyParents(path string) {
	for {
		if err := os.Remove(path); err != nil {
			return
		}
		parent := filepath.Dir(path)
		if parent == path || filepath.Base(parent) == ".claude" || filepath.Base(parent) == ".agents" || filepath.Base(parent) == ".kiro" {
			return
		}
		path = parent
	}
}

func applyOutputs(workdir string, outputs []generatedFile, dryRun bool) ([]string, error) {
	sort.Slice(outputs, func(i, j int) bool { return outputs[i].Path < outputs[j].Path })
	var changes []string
	for _, output := range outputs {
		path := filepath.Join(workdir, filepath.FromSlash(output.Path))
		current, err := os.ReadFile(path)
		if err == nil && bytes.Equal(current, output.Content) {
			continue
		}
		if err != nil && !os.IsNotExist(err) {
			return nil, fmt.Errorf("read %s: %w", output.Path, err)
		}
		if err == nil && !hasGeneratedMarker(current) {
			changes = append(changes, "warning: overwriting existing unmarked file "+output.Path)
		}
		verb := "wrote"
		if dryRun {
			verb = "would write"
		} else {
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				return nil, fmt.Errorf("mkdir %s: %w", filepath.ToSlash(filepath.Dir(path)), err)
			}
			if err := os.WriteFile(path, output.Content, 0o644); err != nil {
				return nil, fmt.Errorf("write %s: %w", output.Path, err)
			}
		}
		changes = append(changes, verb+" "+output.Path)
	}
	return changes, nil
}

func hasGeneratedMarker(contents []byte) bool {
	return bytes.Contains(contents, []byte("Generated by ai-sync. Do not edit directly; source is .ai/."))
}

func mustJSON(value any) []byte {
	contents, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(contents, '\n')
}

func mcpServersJSON(mcp mcpConfig) map[string]any {
	servers := map[string]any{}
	for _, name := range sortedServerNames(mcp.Servers) {
		server := mcp.Servers[name]
		entry := map[string]any{"command": server.Command}
		if len(server.Args) > 0 {
			entry["args"] = server.Args
		}
		if len(server.Env) > 0 {
			entry["env"] = server.Env
		}
		servers[name] = entry
	}
	return servers
}

func sortedServerNames(servers map[string]mcpServer) []string {
	names := make([]string, 0, len(servers))
	for name := range servers {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedFileNames(files map[string][]byte) []string {
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

func sortedStringMapKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func sortedMapKeys(values map[string]string) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func tomlString(value string) string {
	encoded, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(encoded)
}

func tomlStringArray(values []string) string {
	parts := make([]string, 0, len(values))
	for _, value := range values {
		parts = append(parts, tomlString(value))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func tomlBareKey(value string) string {
	if value == "" {
		return tomlString(value)
	}
	for _, r := range value {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_' || r == '-' {
			continue
		}
		return tomlString(value)
	}
	return value
}
