package app_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dialguiba/ai-sync/internal/app"
)

func TestHelpShowsCommandsAndOptions(t *testing.T) {
	dir := t.TempDir()

	out, err := app.Run(dir, []string{"--help"})
	if err != nil {
		t.Fatalf("help should not return an error: %v", err)
	}
	for _, want := range []string{
		"keeps AI-agent configuration",
		"Usage:",
		"ai-sync init",
		"ai-sync convention",
		"ai-sync version",
		"convention        print the .ai authoring convention",
		"version           print version and build metadata",
		"--target claude|codex|kiro",
		"--dry-run",
		"Examples:",
		"See README.md",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("expected help to contain %q, got:\n%s", want, out)
		}
	}
}

func TestVersionShowsBuildMetadata(t *testing.T) {
	dir := t.TempDir()

	info := app.BuildInfo{Version: "v1.2.3", Commit: "abc123", Date: "2026-07-19T00:00:00Z"}
	for _, args := range [][]string{{"version"}, {"--version"}} {
		out, err := app.RunWithBuildInfo(dir, args, info)
		if err != nil {
			t.Fatalf("version should not return an error for args %v: %v", args, err)
		}
		for _, want := range []string{"ai-sync v1.2.3", "commit abc123", "built 2026-07-19T00:00:00Z"} {
			if !strings.Contains(out, want) {
				t.Fatalf("expected version output for args %v to contain %q, got:\n%s", args, want, out)
			}
		}
	}
}

func TestConventionShowsCanonicalAuthoringGuide(t *testing.T) {
	dir := t.TempDir()

	out, err := app.Run(dir, []string{"convention"})
	if err != nil {
		t.Fatalf("convention should not return an error: %v", err)
	}
	for _, want := range []string{
		"# ai-sync .ai Authoring Convention",
		"Create a canonical .ai/ directory",
		".ai/project.md",
		".ai/mcp.yaml",
		".ai/targets/claude.md",
		".ai/targets/codex.md",
		".ai/targets/kiro.md",
		".ai/skills/<name>/SKILL.md",
		"Do not create generated agent files directly",
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("expected convention output to contain %q, got:\n%s", want, out)
		}
	}
}

func TestInitCreatesCanonicalSource(t *testing.T) {
	dir := t.TempDir()

	out, err := app.Run(dir, []string{"init"})
	if err != nil {
		t.Fatalf("Run init returned error: %v", err)
	}
	if !strings.Contains(out, "created .ai") {
		t.Fatalf("expected init output to mention created .ai, got %q", out)
	}

	for _, path := range []string{
		".ai/project.md",
		".ai/mcp.yaml",
		".ai/targets/claude.md",
		".ai/targets/codex.md",
		".ai/targets/kiro.md",
		".ai/skills/example/SKILL.md",
	} {
		assertFileExists(t, filepath.Join(dir, path))
	}
}

func TestSyncGeneratesClaudeCodexAndKiroOutputs(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	out, err := app.Run(dir, nil)
	if err != nil {
		t.Fatalf("Run sync returned error: %v", err)
	}
	if !strings.Contains(out, "wrote CLAUDE.md") || !strings.Contains(out, "wrote AGENTS.md") || !strings.Contains(out, "wrote .kiro/steering/project-conventions.md") {
		t.Fatalf("expected output to list generated files, got %q", out)
	}

	assertFileContains(t, filepath.Join(dir, "CLAUDE.md"), "Use conventional commits")
	assertFileContains(t, filepath.Join(dir, "CLAUDE.md"), "Claude-specific guidance")
	assertFileContains(t, filepath.Join(dir, "AGENTS.md"), "Codex-specific guidance")
	assertFileContains(t, filepath.Join(dir, ".kiro/steering/project-conventions.md"), "Kiro-specific guidance")

	assertFileContains(t, filepath.Join(dir, ".mcp.json"), "playwright")
	assertFileContains(t, filepath.Join(dir, ".codex/config.toml"), `[mcp_servers.playwright]`)
	assertFileContains(t, filepath.Join(dir, ".kiro/settings/mcp.json"), "mcpServers")

	assertFileContains(t, filepath.Join(dir, ".claude/skills/playwright-cli/SKILL.md"), "Playwright CLI")
	assertFileContains(t, filepath.Join(dir, ".agents/skills/playwright-cli/SKILL.md"), "Playwright CLI")
	kiroPower, err := os.ReadFile(filepath.Join(dir, ".kiro/powers/playwright-cli/POWER.md"))
	if err != nil {
		t.Fatalf("read generated Kiro Power: %v", err)
	}
	if !strings.HasPrefix(string(kiroPower), "---\nname: \"playwright-cli\"") {
		t.Fatalf("expected Kiro Power frontmatter to stay at file start, got:\n%s", string(kiroPower))
	}
	assertFileContains(t, filepath.Join(dir, ".kiro/powers/playwright-cli/POWER.md"), "Generated by ai-sync")
}

func TestSyncIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	if _, err := app.Run(dir, nil); err != nil {
		t.Fatalf("first sync failed: %v", err)
	}
	first := snapshotFiles(t, dir, []string{
		"CLAUDE.md",
		"AGENTS.md",
		".mcp.json",
		".codex/config.toml",
		".kiro/settings/mcp.json",
		".kiro/powers/playwright-cli/POWER.md",
		".kiro/powers/playwright-cli/.ai-sync-manifest",
	})

	out, err := app.Run(dir, nil)
	if err != nil {
		t.Fatalf("second sync failed: %v", err)
	}
	if !strings.Contains(out, "no changes") {
		t.Fatalf("expected no changes output, got %q", out)
	}
	second := snapshotFiles(t, dir, []string{
		"CLAUDE.md",
		"AGENTS.md",
		".mcp.json",
		".codex/config.toml",
		".kiro/settings/mcp.json",
		".kiro/powers/playwright-cli/POWER.md",
		".kiro/powers/playwright-cli/.ai-sync-manifest",
	})
	if first != second {
		t.Fatalf("expected second sync to preserve generated bytes")
	}
}

func TestSyncPrunesStaleGeneratedSkillOutputs(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	if _, err := app.Run(dir, nil); err != nil {
		t.Fatalf("initial sync failed: %v", err)
	}
	if err := os.RemoveAll(filepath.Join(dir, ".ai/skills/playwright-cli")); err != nil {
		t.Fatalf("remove source skill: %v", err)
	}

	out, err := app.Run(dir, nil)
	if err != nil {
		t.Fatalf("sync after skill removal failed: %v", err)
	}
	if !strings.Contains(out, "removed .agents/skills/playwright-cli/SKILL.md") || !strings.Contains(out, "removed .kiro/powers/playwright-cli/POWER.md") {
		t.Fatalf("expected stale generated skill files to be pruned, got %q", out)
	}
	assertFileMissing(t, filepath.Join(dir, ".claude/skills/playwright-cli"))
	assertFileMissing(t, filepath.Join(dir, ".agents/skills/playwright-cli"))
	assertFileMissing(t, filepath.Join(dir, ".kiro/powers/playwright-cli"))
}

func TestPrunePreservesUserOwnedFilesInGeneratedSkillDirs(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	if _, err := app.Run(dir, nil); err != nil {
		t.Fatalf("initial sync failed: %v", err)
	}
	writeFile(t, dir, ".agents/skills/playwright-cli/user-notes.md", "do not delete\n")
	if err := os.RemoveAll(filepath.Join(dir, ".ai/skills/playwright-cli")); err != nil {
		t.Fatalf("remove source skill: %v", err)
	}

	if _, err := app.Run(dir, nil); err != nil {
		t.Fatalf("sync after skill removal failed: %v", err)
	}
	assertFileExists(t, filepath.Join(dir, ".agents/skills/playwright-cli/user-notes.md"))
	assertFileMissing(t, filepath.Join(dir, ".agents/skills/playwright-cli/SKILL.md"))
}

func TestPruneIgnoresManualSkillDirsWithoutManifest(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)
	writeFile(t, dir, ".agents/skills/manual/SKILL.md", "# Manual\n")

	if _, err := app.Run(dir, []string{"--target", "codex"}); err != nil {
		t.Fatalf("targeted sync failed: %v", err)
	}
	assertFileExists(t, filepath.Join(dir, ".agents/skills/manual/SKILL.md"))
}

func TestDryRunPruneDoesNotDeleteFiles(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	if _, err := app.Run(dir, nil); err != nil {
		t.Fatalf("initial sync failed: %v", err)
	}
	if err := os.RemoveAll(filepath.Join(dir, ".ai/skills/playwright-cli")); err != nil {
		t.Fatalf("remove source skill: %v", err)
	}

	out, err := app.Run(dir, []string{"--dry-run"})
	if err != nil {
		t.Fatalf("dry-run prune failed: %v", err)
	}
	if !strings.Contains(out, "would remove .agents/skills/playwright-cli/SKILL.md") {
		t.Fatalf("expected dry-run prune output, got %q", out)
	}
	assertFileExists(t, filepath.Join(dir, ".agents/skills/playwright-cli/SKILL.md"))
}

func TestTargetFlagOnlyGeneratesSelectedTarget(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	out, err := app.Run(dir, []string{"--target", "codex"})
	if err != nil {
		t.Fatalf("targeted sync failed: %v", err)
	}
	if !strings.Contains(out, "wrote AGENTS.md") {
		t.Fatalf("expected codex output, got %q", out)
	}
	assertFileExists(t, filepath.Join(dir, "AGENTS.md"))
	assertFileMissing(t, filepath.Join(dir, "CLAUDE.md"))
	assertFileMissing(t, filepath.Join(dir, ".kiro/steering/project-conventions.md"))
}

func TestDryRunDoesNotWriteFiles(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	out, err := app.Run(dir, []string{"--dry-run"})
	if err != nil {
		dryRunReturnedError := err
		t.Fatalf("dry run failed: %v", dryRunReturnedError)
	}
	if !strings.Contains(out, "would write CLAUDE.md") {
		t.Fatalf("expected dry-run output, got %q", out)
	}
	assertFileMissing(t, filepath.Join(dir, "CLAUDE.md"))
	assertFileMissing(t, filepath.Join(dir, "AGENTS.md"))
}

func TestUnknownTargetReturnsActionableError(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)

	_, err := app.Run(dir, []string{"--target", "junie"})
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "expected claude, codex, or kiro") {
		t.Fatalf("expected actionable target error, got %v", err)
	}
}

func TestMalformedMCPYAMLReturnsParseError(t *testing.T) {
	dir := t.TempDir()
	writeCanonicalSource(t, dir)
	writeFile(t, dir, ".ai/mcp.yaml", "servers:\n  broken: [\n")

	_, err := app.Run(dir, nil)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "parse .ai/mcp.yaml") {
		t.Fatalf("expected MCP parse error, got %v", err)
	}
}

func TestSyncWithoutCanonicalSourceReturnsActionableError(t *testing.T) {
	dir := t.TempDir()

	_, err := app.Run(dir, nil)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "run `ai-sync init`") {
		t.Fatalf("expected actionable init hint, got %v", err)
	}
}

func writeCanonicalSource(t *testing.T, dir string) {
	t.Helper()
	writeFile(t, dir, ".ai/project.md", "# Project\n\nUse conventional commits.\n")
	writeFile(t, dir, ".ai/targets/claude.md", "# Claude\n\nClaude-specific guidance.\n")
	writeFile(t, dir, ".ai/targets/codex.md", "# Codex\n\nCodex-specific guidance.\n")
	writeFile(t, dir, ".ai/targets/kiro.md", "# Kiro\n\nKiro-specific guidance.\n")
	writeFile(t, dir, ".ai/mcp.yaml", `servers:
  playwright:
    command: npx
    args:
      - -y
      - '@playwright/mcp@latest'
    env:
      PLAYWRIGHT_HEADLESS: "true"
`)
	writeFile(t, dir, ".ai/skills/playwright-cli/SKILL.md", `---
name: "playwright-cli"
description: "Use Playwright from the CLI."
---

# Playwright CLI

Use Playwright for browser checks.
`)
}

func writeFile(t *testing.T, root, rel, content string) {
	t.Helper()
	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

func assertFileExists(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("expected file %s to exist: %v", path, err)
	}
}

func assertFileMissing(t *testing.T, path string) {
	t.Helper()
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("expected file %s to be missing, stat err=%v", path, err)
	}
}

func assertFileContains(t *testing.T, path, want string) {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	if !strings.Contains(string(contents), want) {
		t.Fatalf("expected %s to contain %q, got:\n%s", path, want, string(contents))
	}
}

func snapshotFiles(t *testing.T, root string, rels []string) string {
	t.Helper()
	var b strings.Builder
	for _, rel := range rels {
		contents, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Fatalf("read %s: %v", rel, err)
		}
		b.WriteString("--- ")
		b.WriteString(rel)
		b.WriteString("\n")
		b.Write(contents)
		b.WriteString("\n")
	}
	return b.String()
}
